spring:
  application:
    name: login

  datasource:
    url: jdbc:postgresql://localhost:5432/login_dev
    username: postgres
    password: 491273
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

server:
  port: 8081

app:
  token:
    secret-key: ${JWT_SECRET_KEY:QXJhdGVjaC1TaXN0ZW1hcy1RTW92aS1Mb2dpbg==}
